### ISSUE TITLE
What is sbt-freestyle?

### ISSUE THREAD

**Issue by dwijnand** [frees-io/sbt-freestyle#32]
The GitHub repo's description and README say "sbt-plugin for Freestyle projects".
On http://frees.io/ I see no mention of sbt-freestyle.
In FreestylePlugin.scala it says "A Cohesive & Pragmatic Framework of FP centric Scala libraries".

Is sbt-freestyle an sbt plugin for the projects in the frees-io org (like sbt/sbt-houserules, scala/sbt-scala-module and playframework/interplay)? Or is it for general consumption?

**Comment by juanpedromoreno** [comment]
Hi @dwijnand . Sorry about the confusion. 

`sbt-freestyle` it's just a bridge between [sbt-org-policies](https://github.com/47deg/sbt-org-policies) and all the projects within of `frees-io` organization.

Its main responsibility is to set up common configurations across all the freestyle projects, as well as providing some sbt settings, tasks, commands, and utilities offered by the `sbt-org-policies` plugin. Hence, it might not have sense using it outside the `frees-io` organization.

**Comment by dwijnand** [comment]
Cool. Thank you for clearing that up.
